---
# TODO
# crossplane package/configurartion metadata
# build with `$ kubectl crossplane build configuration`- this creates an xpkg file.
# `$ REG=myrepo; kubectl crossplane pussh configurartion ${REG}/<config-name:version>`
apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: confluent-platform
  annotations:
    provider: ["kubernetes", "helm"]
spec:
  crossplane:
    version: ">=v1.4.0-0"
  dependsOn:
    - provider: crossplane/provider-kubernetes
      version: ">=v0.5.0"
    - provider: crossplane/provider-helm
      version: ">=v0.11.1"
