---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xp-providers
rules:
  - apiGroups: ["", "apiextensions.k8s.io", "rbac.authorization.k8s.io", "apps", "networking.k8s.io", "platform.confluent.io", "policy", "route.openshift.io"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modify-namespace-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: xp-providers
subjects:
- kind: ServiceAccount
  name: provider-helm-aee3629a3156
  namespace: crossplane-system
- kind: ServiceAccount
  name: provider-kubernetes-f935b3d8b7ec
  namespace: crossplane-system
