---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
 name: provider-helm
spec:
 package: "crossplane/provider-helm:v0.11.1"

---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: local
spec:
  credentials:
    source: InjectedIdentity

---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
 name: xpaks1
spec:
 credentials:
   source: Secret
   secretRef:
     namespace: crossplane-system
     name: mboxpaks1-connDetails
     key: kubeconfig
