apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cfk-crossplane
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: cfk-crossplane
  targetNamespace: default
