apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cfk-crossplane
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomization
  prune: true
  sourceRef:
    kind: GitRepository
    name: cfk-crossplane
  targetNamespace: default
  healthChecks:
    - apiVersion: "helm.crossplane.io/v1beta1"
      kind: ProviderConfig
      name: provider-helm
      namespace: crossplane-system
  timeout: 2m
